### ISSUE TITLE
readme: change $ poetry run init  ...to... $ poetry run

### ISSUE THREAD

**Issue by apolopena** [hackersandslackers/python-poetry-tutorial#1]
Currently if you follow the instructions in the readme you will get something like the following error when running the command `$ poetry run init`: 
```
[FileNotFoundError]
[WinError 2] The system cannot find the file specified
```
Rather you must type `$poetry run` to run the program.

**Comment by toddbirchard** [comment]
Fixed, thanks @apolopena !
